title: "Red de IA aplicada al Proceso de Desarrollo de Software"
description: "Catálogo de universidades, herramientas y repos de la Red"
lang: es
timezone: Europe/Madrid
url: ""
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

navigation:
  - title: "Inicio"
    url: /
  - title: "Universidades"
    url: /universidades/
  - title: "Herramientas y Repositorios"
    url: /herramientas/

minimal_mistakes_skin: default
logo: /assets/img/logo-avatar.png
search: true

author:
  name: "Red IA4Software"
  avatar: /assets/img/logo-avatar.png

collections:
  pages:
    output: true
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      toc: true
      toc_label: "Contenido"
      toc_sticky: true
